#!/bin/bash
rm ~/Dotfiles/i3/config
rm ~/Dotfiles/i3status.conf
rm ~/Dotfiles/config/ranger/bookmarks
ln -s ~/Dotfiles/sPluto/i3/config ~/Dotfiles/i3/
ln -s ~/Dotfiles/sPluto/i3status.conf ~/Dotfiles/
ln -s ~/Dotfiles/sPluto/config/ranger/bookmarks ~/Dotfiles/config/ranger/
