#!/bin/bash
rm ~/Dotfiles/i3/config
rm ~/Dotfiles/i3status.conf
rm ~/Dotfiles/config/ranger/bookmarks
ln ~/Dotfiles/sMars/i3/config ~/Dotfiles/i3/
ln ~/Dotfiles/sMars/i3status.conf ~/Dotfiles/
ln ~/Dotfiles/sMars/config/ranger/bookmarks ~/Dotfiles/config/ranger/
